### ISSUE TITLE
File Based Compilation

### ISSUE THREAD

**Issue by felipeochoa** [dgorissen/pycel#4]
Have you taken a look at [openpyxl](https://bitbucket.org/ericgazoni/openpyxl) for parsing  `xlsx` files? I realize it can't handle the old `xls` format, but I think they've figured out their formula-parsing problems from earlier. Would be nice to remove the COM requirement.

**Comment by willu47** [comment]
New link https://bitbucket.org/openpyxl/openpyxl

**Comment by phrrngtn** [comment]
I did some of this yesterday and it seems to work OK. I will attempt to package it up and send it as a pull request.

**Comment by phrrngtn** [comment]
The problem is when the openxml for the workbook uses shared *formulae* that openpyxl does not ready it correctly. I read the documentation on the schema ( https://msdn.microsoft.com/en-us/library/office/documentformat.openxml.spreadsheet.cellformula.aspx ) and it seems that the way Excel is interpreting this groups of cells is "E112 has a shared formula and it applies to cells E112:F112 and the definition of the formula is E109+E110+E111. Please take any cells in the applicable range and interpret the relative addresses appropriately". This seems *really* difficult to get correct without parsing the formula fully so that when you attempt to access the formula in any of the cells that share this formula that you 'patch' the relative references appropriately. I will open up a ticket with the openpyxl project (if there is not already one there). This seems like a pretty hard problem to workaround?

```xml
<row r="112" spans="2:8" s="72" customFormat="1" x14ac:dyDescent="0.25">
<c r="D112" s="85">
<f>D109+D110+D111</f>
<v>1.1351256454568353</v>
</c>
<c r="E112" s="85">
<f t="shared" ref="E112:F112" si="0">E109+E110+E111</f>
<v>0.9929493738529338</v>
</c>
<c r="F112" s="85">
<f t="shared" si="0"/>
<v>1.3154826664610835</v>
</c>
```

**Comment by phrrngtn** [comment]
Here is an already open ticket on the topic in openpyxl 
https://bitbucket.org/openpyxl/openpyxl/issue/435/incomplete-read-with-extended-cells

It may make sense to extract out the parser/tokenizer completely out of this package so that it can be used by openpyxl as part of the reader code.

**Comment by ankostis** [comment]
What about the [Lexer+Parser](https://github.com/python-excel/xlwt/blob/master/xlwt/ExcelFormulaLexer.py) from [*xlwt* project](https://github.com/python-excel/xlwt)?

**Comment by felipeochoa** [comment]
Openpyxl now has its own formula parser and handles shared formulae properly (except for one outstanding corner case I need to fix)

**Comment by vallettea** [comment]
@felipeochoa I can't see this PR on github. Can you point out where it is ?
Thanks for the comment

**Comment by felipeochoa** [comment]
https://bitbucket.org/openpyxl/openpyxl/pull-requests/72

**Comment by vallettea** [comment]
thanks a lot, nice work.
